#!/bin/bash
########################################################################
# TODO:
# j-b on #videolan:
# Ubuntu 14.04 is the oldest version supported by VLC 3
# <j-b> use extras/tools;
# <j-b> use contribs (for alsa)
# <j-b> use contribs with --disable to disable bluray
# <j-b> don't disable cddb
# <j-b> don't compile with gcc 4.9 but 6.1
# <j-b> don't build with Qt4, but qith qt5
# <j-b> once this is done, we can retalk :0
########################################################################
## Set env variables
#Needed to export all possible pkgconfig paths to prevent pkgconfig failures in tools and contribs.
export PATH=/app/usr/bin:/vlc/extras/tools/build/bin/:/vlc/contrib/x86_64-linux-gnu/bin:$PATH
export LD_LIBRARY_PATH=/app/usr/lib:/vlc/extras/tools/build/lib:/vlc/contrib/x86_64-linux-gnu/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/app/usr/lib/pkgconfig:/app/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/vlc/contrib/x86_64-linux-gnu/lib/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH
export ACLOCAL_PATH=/app/usr/share/aclocal:/usr/share/aclocal:$ACLOCAL_PATH
# Build failures without this, putting at top for consistancy
#export CFLAGS="-fPIC"
#export CXXFLAGS="-Wl,--no-as-needed"
VLC_PREFIX=/app/usr
ARCH=$(arch)
APP=vlc
VERSION=3.0.0-git
export DEBIAN_FRONTEND=noninteractive

# Install what we can via packages
sudo apt-get update
sudo apt-get -y install  autoconf cvs libopenvg1-mesa-dev software-properties-common \
libgtk-3-dev libdbus-1-dev libgtk2.0-dev libsystemd-daemon-dev \
liblivemedia-dev libdc-dev libraw-dev libgdk-pixbuf2.0-dev shared-mime-info \
libsmbclient-dev libfreerdp-dev libshine-dev libgstreamer1.0-dev libva-x11-1 libva-drm1  \
python3-dev libprojectm-dev libavahi-client-dev libncurses5-dev libmtp-dev libudev-dev libva-dev \
libsecret-1-dev libxt-dev libfontenc-dev curl gstreamer1.0-plugins-base mercurial libpulse-dev \
libsoxr-dev libx11-dev libfontconfig1-dev libfreetype6-dev libxext-dev libxfixes-dev libxi-dev \
libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev \
libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev \
libxcb-randr0-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-composite0-dev \
libxcb-xv0-dev libsoxr-dev libupnp6-dev libxfont-dev libfs-dev libxss-dev \
libxmu-dev libxpm-dev libxaw7-dev libxres-dev libxtst-dev libxv-dev libxvmc-dev libxxf86dga-dev \
libdmx-dev libpciaccess-dev libxkbfile-dev libvorbis-dev libogg-dev liblua5.2-dev lua5.2 libmpg123-dev \
liba52-0.7.4-dev libgsm1-dev libmp3lame-dev libopenjpeg-dev libpng-dev

# Don't use ubuntu libtool as it is too old.
# Workaround for
# autoreconf: running: automake --add-missing --copy --force-missing
# configure.ac:7: error: must install xorg-macros 1.12 or later before running autoconf/autogen
# configure.ac:7: the top level
# autom4te: /usr/bin/m4 failed with exit status: 1
# aclocal: error: echo failed with exit status: 1
# autoreconf: aclocal failed with exit status: 1
# make: *** [.xproto] Error 1
#
# cd /usr/src
# wget http://ftp.x.org/pub/individual/util/util-macros-1.19.0.tar.bz2
# tar -jxvf util-macros-1.19.0.tar.bz2
# cd util-macros-1.19.0
# ./configure --prefix /usr
# make install

########################################################################
# Get VLC
########################################################################

cd /
git clone git://git.videolan.org/vlc.git --depth 1
cd vlc
# wget https://raw.githubusercontent.com/appimage-packages/vlc3/master/gpg-error_gettext_dep.patch
# patch -p1 < gpg-error_gettext_dep.patch
#Workaround
#mv /vlc/contrib/x86_64-linux-gnu/plugins/platforms/libqwindows.a /vlc/contrib/x86_64-linux-gnu/lib/ && rm -rf /vlc/contrib/x86_64-linux-gnu/plugins
#mv: cannot stat '/vlc/contrib/x86_64-linux-gnu/plugins/platforms/libqwindows.a': No such file or directory
#make: *** [.qt] Error 1
#make: *** Waiting for unfinished jobs..
sed -i '/libqwindows.a/d' contrib/src/qt/rules.mak
sed -i 's/-lqwindows//' contrib/src/qt/rules.mak
#sed -i 's/-static//' contrib/src/qt/rules.mak

########################################################################
# To-be-built packages: autoconf automake cmake yasm ragel protoc ant
########################################################################

# Workaround for:
# Connecting to cmake.org (cmake.org)|66.194.253.19|:443... connected.
# ERROR: no certificate subject alternative name matches
# 	requested host name `cmake.org'.
# To connect to cmake.org insecurely, use `--no-check-certificate'.
echo "check_certificate = off" > $HOME/.wgetrc

cd extras/tools/
./bootstrap
make -j 8

########################################################################
# Install newer versions of some build-time dependencies
# These need to be enabled or disabled at bootstrap. Unfortunately, these do NOT
# build in any logical order and therefore dependency chains are broken and I had to build
# them outside contribs.
########################################################################

# Workaround for:
# Getting warning about outdated gettext
# Update gettext to 0.19.6
# We can't use contrib version due to
#aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
#autoreconf: Entering directory `.'
#autoreconf: running: autopoint --force
#Can't exec "autopoint": No such file or directory at /vlc/extras/tools/build/share/autoconf/Autom4te/FileUtils.pm line 345.
#autoreconf: failed to run autopoint: No such file or directory
#autoreconf: autopoint is needed because this package uses Gettext
#make: *** [.gpg-error] Error 1
#make: *** Waiting for unfinished jobs....
# In other words build order is broken.
# Included patch adding DEPS_gpg-error = gettext did not have the success I was hoping for.
# cd /usr/src
# wget -c -T 10 ftp://ftp.gnu.org/gnu/gettext/gettext-0.19.7.tar.gz
# tar xvf gettext-0.19.7.tar.gz
# cd gettext-0.19.7
# ./configure --prefix=/usr --enable-static
# make -j 8 && make install
# chmod -v 0755 /usr/lib/preloadable_libintl.so

#Workaround for glibc and gcc6
#gdate.c: In function 'g_date_strftime':
#gdate.c:2497:7: error: format not a string literal, format string not checked [-Werror=format-nonliteral]
#       tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
#       ^~~~~~
#  CC       libglib_2_0_la-gdir.lo
#  CC       libglib_2_0_la-genviron.lo
#  CC       libglib_2_0_la-gerror.lo
#  CC       libglib_2_0_la-gfileutils.lo
#  CC       libglib_2_0_la-ggettext.lo
#  CC       libglib_2_0_la-ghash.lo
#cc1: some warnings being treated as errors
#make[5]: *** [libglib_2_0_la-gdate.lo] Error 1
#make[5]: *** Waiting for unfinished jobs..''
# ffi is a dep of glib
# FFI_VERSION=3.0.13
# FFI_URL=ftp://sourceware.org/pub/libffi/libffi-$FFI_VERSION.tar.gz
# wget $FFI_URL
# tar -xvzf libffi-$FFI_VERSION.tar.gz
# cd libffi-$FFI_VERSION
# ./configure --prefix=/app/usr
# make -j 8 && make install
#
# GLIB_VERSION=2.38
# GLIB_MINOR_VERSION=2.38.2
# GLIB_URL=http://ftp.gnome.org/pub/gnome/sources/glib/$GLIB_VERSION/glib-$GLIB_MINOR_VERSION.tar.xz
# cd /usr/src
# wget $GLIB_URL
# tar -xvf glib-$GLIB_MINOR_VERSION.tar.xz
# cd glib-$GLIB_MINOR_VERSION
# ./configure --prefix=/app/usr
# make -j 8 && make install
#
# cd /vlc

########################################################################
# The "Contrib" method.
# If the libraries are not provided by your distribution,
# you may be better off linking VLC with them statically.
########################################################################
#Add new tools to PATH
export PATH=/app/usr/bin:/vlc/extras/tools/build/bin/:/vlc/contrib/x86_64-linux-gnu/bin:$PATH
export LD_LIBRARY_PATH=/app/usr/lib:/vlc/extras/tools/build/lib:/vlc/contrib/x86_64-linux-gnu/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/app/usr/lib/pkgconfig:/app/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/vlc/contrib/x86_64-linux-gnu/lib/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH
export ACLOCAL_PATH=/usr/share/aclocal:$ACLOCAL_PATH

cd /vlc/contrib
mkdir native
cd native

#Workaround for dependency issues in build order we have to run this several times.
# I tried patching DEP_gettext to problem contribs but it did not have the outcome I expected, aka it still failed.
../bootstrap --prefix=/app/usr --enable-xorg-macros --enable-gettext --disable-qt  --disable-openjpeg --disable-ffmpeg --disable-SDL_image --disable-a52dec --disable-a52 \
 --disable-aribb24 --disable-aribb25 --disable-asdcplib --disable-ass --disable-bghudappkit --disable-bluray \
 --disable-bpg --disable-caca --disable-cddb --disable-chromaprint --disable-crystalhd --disable-d3d11 \
 --disable-d3d9 --disable-daala --disable-dca --disable-directx --disable-dshow --disable-dvbpsi \
 --disable-dvdcss --disable-dvdread --disable-dvdnav --disable-libebml --disable-faad2 --disable-ffi \
 --disable-flac --disable-gsml --disable-fluid --disable-fluidlite --disable-fontconfig \
 --disable-freetype2 --disable-fribidi --disable-gcrypt --disable-glew --enable-glib --disable-gme \
 --disable-gmp --disable-gnutls --disable-goom --disable-gpg-error --disable-growl  --disable-gsm \
 --disable-harfbuzz --disable-iconv --disable-jack --disable-jpeg --disable-kate --disable-lame \
 --disable-libarchive --disable-libdsm --disable-libmpeg2 --disable-libtasn1 --disable-libxml2 \
 --disable-live555 --disable-lua --disable-mad --disable-matroska --disable-mfx --disable-microdns \
 --disable-modplug --disable-mpcdec --disable-mpg123 --disable-ncurses --disable-nettle --disable-nfs\
 --disable-ogg --disable-opus --disable-orc --disable-png --disable-postproc \
 --disable-projectM --disable-protobuf --disable-pthreads --disable-regex \
 --disable-samplerate --disable-schroedinger --disable-sdl --disable-shout --disable-sidplay2 \
 --disable-soxr --disable-sparkle --disable-speex --disable-speexdsp --disable-sqlite --disable-ssh2 \
 --disable-taglib --disable-theora --disable-tiff --disable-tiger --disable-tremor --disable-twolame \
 --disable-upnp --disable-vncclient --disable-vorbis --disable-vpx --disable-x264 --disable-x265 \
 --disable-xau --disable-xcb-proto --disable-xcb --disable-xproto --disable-zlib \
 --disable-zvbi

make -j 8

../bootstrap --prefix=/app/usr --disable-xorg-macros --disable-gettext --enable-qt  --enable-openjpeg \
 --disable-ffmpeg --disable-SDL_image --disable-a52dec --disable-a52 \
 --disable-aribb24 --disable-aribb25 --disable-asdcplib --disable-ass --disable-bghudappkit --disable-bluray \
 --disable-bpg --disable-caca --enable-cddb --disable-chromaprint --disable-crystalhd --disable-d3d11 \
 --disable-d3d9 --disable-daala --disable-dca --disable-directx --disable-dshow --disable-dvbpsi \
 --disable-dvdcss --disable-dvdread --disable-dvdnav --disable-libebml --disable-faad2 --disable-ffi \
 --disable-flac --disable-gsml --disable-fluid --disable-fluidlite --disable-fontconfig \
 --disable-freetype2 --disable-fribidi --disable-gcrypt --disable-glew --enable-glib --disable-gme \
 --disable-gmp --disable-gnutls --disable-goom --disable-gpg-error --disable-growl  --disable-gsm \
 --disable-harfbuzz --disable-iconv --disable-jack --disable-jpeg --disable-kate --disable-lame \
 --disable-libarchive --disable-libdsm --disable-libmpeg2 --disable-libtasn1 --disable-libxml2 \
 --disable-live555 --disable-lua --disable-mad --disable-matroska --disable-mfx --disable-microdns \
 --disable-modplug --disable-mpcdec --disable-mpg123 --disable-ncurses --disable-nettle --disable-nfs\
 --disable-ogg --disable-opus --disable-orc --disable-png --disable-postproc \
 --disable-projectM --disable-protobuf --disable-pthreads --disable-regex \
 --disable-samplerate --disable-schroedinger --disable-sdl --disable-shout --disable-sidplay2 \
 --disable-soxr --disable-sparkle --disable-speex --disable-speexdsp --disable-sqlite --disable-ssh2 \
 --disable-taglib --disable-theora --disable-tiff --disable-tiger --disable-tremor --disable-twolame \
 --disable-upnp --disable-vncclient --disable-vorbis --enable-vpx --disable-x264 --disable-x265 \
 --disable-xau --disable-xcb-proto --disable-xcb --disable-xproto --disable-zlib \
 --disable-zvbi


make -j 8

../bootstrap --prefix=/app/usr --disable-xorg-macros --disable-gettext --disable-qt  --disable-openjpeg \
 --enable-ffmpeg --disable-SDL_image --disable-a52dec --disable-a52 \
 --disable-aribb24 --disable-aribb25 --disable-asdcplib --disable-ass --disable-bghudappkit --disable-bluray \
 --disable-bpg --disable-caca --disable-cddb --disable-chromaprint --disable-crystalhd --disable-d3d11 \
 --disable-d3d9 --disable-daala --disable-dca --disable-directx --disable-dshow --disable-dvbpsi \
 --disable-dvdcss --disable-dvdread --disable-dvdnav --disable-libebml --disable-faad2 --disable-ffi \
 --disable-flac --disable-gsml --disable-fluid --disable-fluidlite --disable-fontconfig \
 --disable-freetype2 --disable-fribidi --disable-gcrypt --disable-glew --disable-glib --disable-gme \
 --disable-gmp --disable-gnutls --disable-goom --disable-gpg-error --disable-growl  --disable-gsm \
 --disable-harfbuzz --disable-iconv --disable-jack --disable-jpeg --disable-kate --disable-lame \
 --disable-libarchive --disable-libdsm --disable-libmpeg2 --disable-libtasn1 --disable-libxml2 \
 --disable-live555 --disable-lua --disable-mad --disable-matroska --disable-mfx --disable-microdns \
 --disable-modplug --disable-mpcdec --disable-mpg123 --disable-ncurses --disable-nettle --disable-nfs\
 --disable-ogg --disable-opus --disable-orc --disable-png --disable-postproc \
 --disable-projectM --disable-protobuf --disable-pthreads --disable-regex \
 --disable-samplerate --disable-schroedinger --disable-sdl --disable-shout --disable-sidplay2 \
 --disable-soxr --disable-sparkle --disable-speex --disable-speexdsp --disable-sqlite --disable-ssh2 \
 --disable-taglib --disable-theora --disable-tiff --disable-tiger --disable-tremor --disable-twolame \
 --disable-upnp --disable-vncclient --disable-vorbis --disable-vpx --disable-x264 --disable-x265 \
 --disable-xau --disable-xcb-proto --disable-xcb --disable-xproto --disable-zlib \
 --disable-zvbi --disable-luac --disable-libvorbis --disable-libogg

make -j 8
cd /
# ########################################################################
# # These are the failed contribs done manually
# # Most of them failed due to depending on another contrib and there was no method
# # that I could find to force build order.
# ########################################################################
#
# #libcdio too old
# cd /usr/src
# wget http://ftp.gnu.org/gnu/libcdio/libcdio-0.93.tar.bz2
# tar -jxvf libcdio-0.93.tar.bz2
# cd libcdio-0.93
# ./configure --prefix=/usr
# make -j8
# make install
#
# cd /usr/src
# wget https://sourceforge.net/projects/libcddb/files/libcddb/1.3.2/libcddb-1.3.2.tar.bz2
# tar -jxvf libcddb-1.3.2.tar.bz2
# cd libcddb-1.3.2
# ./configure --prefix=/usr
# make -j8
# make install
#
cd /usr/src
wget ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.1.tar.bz2
tar -jxvf alsa-lib-1.1.1.tar.bz2
cd alsa-lib-1.1.1
./configure --prefix=/usr
make -j8
make install
#
# # # x11 libs are too old
# # cd /usr/src
# # cat > lib-7.7.md5 << EOF
# # a615e17d9fee6f097fc3b716eacb3dca  xtrans-1.3.4.tar.bz2
# # c35d6ad95b06635a524579e88622fdb5  libX11-1.6.2.tar.bz2
# # 0d9f6dd9c23bf4bcbfb00504b566baf5  libXfont2-2.0.1.tar.bz2
# # 52df7c4c1f0badd9f82ab124fb32eb97  libXext-1.3.3.tar.bz2
# # a8a0dbd2299b2568d8c919883f5c8501  libFS-1.0.6.tar.bz2
# # addfb1e897ca8079531669c7c7711726  libICE-1.0.9.tar.bz2
# # 499a7773c65aba513609fe651853c5f3  libSM-1.2.2.tar.bz2
# # 7a773b16165e39e938650bcc9027c1d5  libXScrnSaver-1.2.2.tar.bz2
# # 03149823ae57bb02d0cec90d5b97d56c  libXt-1.1.4.tar.bz2
# # 41d92ab627dfa06568076043f3e089e4  libXmu-1.1.2.tar.bz2
# # 769ee12a43611cdebd38094eaf83f3f0  libXpm-3.5.11.tar.bz2
# # 7446f5fba888672aad068b29c0928ba3  libXaw-1.0.12.tar.bz2
# # b985b85f8b9386c85ddcfe1073906b4d  libXfixes-5.0.1.tar.bz2
# # f7a218dcbf6f0848599c6c36fc65c51a  libXcomposite-0.4.4.tar.bz2
# # 2bd9a15fcf64d216e63b8d129e4f1f1c  libXrender-0.9.8.tar.bz2
# # 1e7c17afbbce83e2215917047c57d1b3  libXcursor-1.1.14.tar.bz2
# # 0cf292de2a9fa2e9a939aefde68fd34f  libXdamage-1.1.4.tar.bz2
# # ad2919764933e075bb0361ad5caa3d19  libfontenc-1.1.2.tar.bz2
# # 664629bfa7cdf8b984155019fd395dcb  libXfont-1.5.0.tar.bz2
# # 331b3a2a3a1a78b5b44cfbd43f86fcfe  libXft-2.3.2.tar.bz2
# # 9c4a69c34b19ec1e4212e849549544cb  libXi-1.7.4.tar.bz2
# # 9336dc46ae3bf5f81c247f7131461efd  libXinerama-1.1.3.tar.bz2
# # 210ed9499a3d9c96e3a221629b7d39b0  libXrandr-1.4.2.tar.bz2
# # 45ef29206a6b58254c81bea28ec6c95f  libXres-1.0.7.tar.bz2
# # 25c6b366ac3dc7a12c5d79816ce96a59  libXtst-1.2.2.tar.bz2
# # e0af49d7d758b990e6fef629722d4aca  libXv-1.0.10.tar.bz2
# # 2e4014e9d55c430e307999a6b3dd256d  libXvMC-1.0.8.tar.bz2
# # d7dd9b9df336b7dd4028b6b56542ff2c  libXxf86dga-1.1.4.tar.bz2
# # e46f6ee4f4567349a3189044fe1bb712  libXxf86vm-1.1.3.tar.bz2
# # ba983eba5a9f05d152a0725b8e863151  libdmx-1.1.3.tar.bz2
# # b7c0d3afce14eedca57312a3141ec13a  libpciaccess-0.13.2.tar.bz2
# # 19e6533ae64abba0773816a23f2b9507  libxkbfile-1.0.8.tar.bz2
# # 2dd10448c1166e71a176206a8dfabe6d  libxshmfence-1.1.tar.bz2
# # EOF
# #
# # grep -v '^#' lib-7.7.md5 | awk '{print $2}' | wget -i- -c \
# #     -B http://xorg.freedesktop.org/releases/individual/lib/ &&
# # md5sum -c lib-7.7.md5
# #
# # for package in $(grep -v '^#' lib-7.7.md5 | awk '{print $2}')
# # do
# #   packagedir=${package%.tar.bz2}
# #   tar -xf $package
# #   pushd $packagedir
# #   case $packagedir in
# #     libXfont-[0-9]* )
# #       ./configure  --prefix=/usr \
# #        --disable-devel-docs \
# #        --enable-static
# #     ;;
# #     libXt-[0-9]* )
# #       ./configure  --prefix=/usr \
# #       --with-appdefaultdir=/etc/X11/app-defaults \
# #       --enable-static
# #     ;;
# #     * )
# #       ./configure  --prefix=/usr --enable-static
# #     ;;
# #   esac
# #   make
# #   make install
# #   popd
# #   rm -rf $packagedir
# #   /sbin/ldconfig
# # done
#
########################################################################
# GCC6
# Cannot use new gcc6 on extra-tools to ragel failure http://osdir.com/ml/general/2016-01/msg26911.html
# contribs also had many gcc6 failures. So only building vlc itself with gcc6 as requested.
########################################################################
sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get --yes install  gcc-6 g++-6
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
########################################################################
# Build VLC itself
########################################################################
cd /vlc
export CFLAGS+="-O2 -g -O0 -fPIC"
export CPPFLAGS+="-I/app/usr/include -I/usr/include/ -I/usr/include/x86_64-linux-gnu -I/usr/include/X11/"
export LDLIBS+="$(pkg-config --libs libavutil libavcodec libva x11)"
./bootstrap
./configure --enable-static --disable-chromaprint --disable-bluray --enable-alsa=true --enable-pulse=true --disable-chromecast \
--prefix=$VLC_PREFIX/usr

make -j 8

make install

########################################################################
# Build complete
# Now creating the AppDir
########################################################################
wget -q https://github.com/probonopd/AppImages/raw/master/functions.sh -O ./functions.sh
. ./functions.sh

cd /

cp $VLC_PREFIX/usr/share/applications/vlc.desktop .
sed -i -e "s|Exec=.*|Exec=vlc|g" vlc.desktop
sed -i -e "s|Icon=.*|Icon=vlc.png|g" vlc.desktop
cp $VLC_PREFIX/usr/share/icons/hicolor/48x48/apps/vlc.png .
get_desktopintegration vlc


APPDIR=VLC
mkdir -p /$APPDIR/$APP.AppDir
cd  /$APPDIR/$APP.AppDir
get_apprun
mv /vlc.* .
mkdir -p ./usr/lib/qt5/; mv /vlc/contrib/x86_64-linux-gnu/plugins $_
mkdir -p ./usr/share; mv $VLC_PREFIX/usr/share/vlc $_
mkdir -p ./usr/share/icons; mv $VLC_PREFIX/usr/share/icons/hicolor $_
mv $VLC_PREFIX/usr/share/{applications,mime,locale} ./usr/share
export LD_LIBRARY_PATH=./usr/lib/:$LD_LIBRARY_PATH

patch_usr
move_lib
copy_deps # Three runs to ensure we catch indirect ones
delete_blacklisted
mkdir -p ./usr/bin; mv $VLC_PREFIX/usr/bin/*vlc* $_
mv $VLC_PREFIX/usr/lib/libvlc* ./usr/lib/
mkdir -p ./usr/lib; mv $VLC_PREFIX/usr/lib/vlc $_
mv /vlc/contrib/x86_64-linux-gnu/lib/* ./usr/lib/


# We don't bundle the developer stuff
rm -rf $VLC_PREFIX/usr/include || true
rm -rf $VLC_PREFIX/usr/lib/cmake || true
rm -rf $VLC_PREFIX/usr/lib/pkgconfig || true
rm -rf ./usr/share/doc/vlc/libvlc/ || true
find /$APPDIR/$APP.AppDir/usr/lib/ -name '*.la' | xargs -i rm {}
strip $VLC_PREFIX/usr/bin/* $VLC_PREFIX/usr/lib/* $VLC_PREFIX/usr/lib/vlc/plugins/*/* || true

########################################################################
# AppDir complete
# Now packaging it as an AppImage
########################################################################
cd /$APPDIR
rm /out/* || true
generate_appimage
